# Generated by Django 3.1 on 2020-08-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date'),
        ),
    ]
