# Generated by Django 3.1 on 2020-08-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200821_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
