# Generated by Django 3.1 on 2020-08-25 00:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='finish',
            field=models.BooleanField(default=False, verbose_name='Finish'),
        ),
        migrations.AddField(
            model_name='order',
            name='finish_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Finish date'),
            preserve_default=False,
        ),
    ]
