# Generated by Django 3.1 on 2020-08-25 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200825_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='finish_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finish date'),
        ),
    ]
